import React from 'react';
import styled from 'styled-components';

const StyledSkeleton = styled.table`
  width: 100%;
  border-collapse: collapse;
  th {
    padding: ${({ theme }) => theme.spacings.small2} ${({ theme }) => theme.spacings.small3};
  }
  td {
    padding: ${({ theme }) => theme.spacings.small3} ${({ theme }) => theme.spacings.small3};
  }
  td,
  th {
    vertical-align: top;
    i,
    span {
      width: 100%;
      height: 10px;
      background-color: ${({ theme }) => theme.color.charcoal400};
      animation: ${({ theme }) => theme.animations.loading} 1s infinite ease-in-out;
      border-radius: 2px;
      display: inline-block;
    }

    div {
      display: inline-block;
    }

    i {
      width: 50%;
    }
  }
  thead {
    background-color: ${({ theme }) => theme.color.charcoal300};
    th {
      > span {
        background-color: ${({ theme }) => theme.color.charcoal500};
      }

      &:nth-child(16),
      &:nth-child(15),
      &:nth-child(14),
      &:nth-child(13) {
        background-color: #e5e8ef;
      }
    }
  }

  tbody {
    tr {
      td {
        border-bottom: 1px solid ${({ theme }) => theme.color.charcoal300};
        line-height: 0;
        &:nth-child(16),
        &:nth-child(15),
        &:nth-child(14),
        &:nth-child(13) {
          background-color: #f8f9fa;
        }

        &:nth-child(5),
        &:nth-child(6),
        &:nth-child(7),
        &:nth-child(9),
        &:nth-child(10),
        &:nth-child(13) {
          text-align: right;
        }
      }

      i {
        margin-top: 5px;
      }

      div {
        width: 24px;
        height: 24px;
        border-radius: 4px;
        background-color: ${({ theme }) => theme.color.charcoal400};
        animation: ${({ theme }) => theme.animations.loading} 1s infinite ease-in-out;
      }
    }
  }
`;

const TableSkeleton = React.forwardRef(() => (
  <StyledSkeleton>
    <thead>
      <tr>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
        <th>
          <span></span>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>

      <tr>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
          <i></i>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <div></div>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
    </tbody>
  </StyledSkeleton>
));

TableSkeleton.displayName = 'TableSkeleton';

export default TableSkeleton;
