name: Publish Storybook in develop
on:
  push:
    branches:
      - feature/next-storybook

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: build storybook
        run: yarn build:storybook -o next/next

      - name: Deploy storybook to gh-pages /next
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./next
          keep_files: true
          user_name: 'GH Pages Bot'
          user_email: 'hello@ghbot.com'
          commit_message: 'Deploy to GitHub Pages [skip ci]'
